SELECT NAME
FROM INGREDIENTS I INNER JOIN VENDORS V ON I.VENDORID = V.VENDORID
WHERE V.COMPANYNAME = 'VEGGIES_R_Us';


SELECT I1.NAME
FROM ITEMS I1 INNER JOIN ITEMS I2 ON I1.PRICE > I2.PRICE
WHERE I2.NAME = 'GARDEN SALAD';