SELECT EMPLOYEEID,
CASE
WHEN ASSIGNEDTIME < 0.33 THEN 'PART TIME'
WHEN (ASSIGNEDTIME >=0.33 AND ASSIGNEDTIME < 0.67) THEN 'SPLIT TIME'
WHEN ASSIGNEDTIME >=0.67 THEN 'FULL TIME'
END
AS 'DESCRIPTION'
FROM WORKSON;