--ALTER TABLE PRODUCT_DETAILS ALTER COLUMN PRODUCT_ID NUMERIC(2) NOT NULL;
--ALTER TABLE PRODUCT_DETAILS ADD PRIMARY KEY(PRODUCT_ID);
ALTER TABLE PRODUCT_DETAILS
ADD CONSTRAINT FK_CATEGORY
FOREIGN KEY(CATEGORY_ID)
REFERENCES CATEGORY_DETAILS(CATEGORY_ID),
CONSTRAINT FK_SUB_CATEGORY
FOREIGN KEY(SUB_CATEGORY_ID)
REFERENCES SUB_CATEGORY_DETAILS(SUB_CATEGORY_ID);