DROP TABLE REGISTERED2;
CREATE TABLE REGISTERED2(
COURSENO VARCHAR (9),
IDNO CHAR(13),
GRADE VARCHAR(10),
CONSTRAINT PK_REGISTERED2 PRIMARY KEY(COURSENO, IDNO),
CONSTRAINT FK_CNO  FOREIGN KEY (COURSENO) REFERENCES COURSE ON DELETE CASCADE,
CONSTRAINT FK_IDNO FOREIGN KEY (IDNO) REFERENCES STUDENTS ON DELETE CASCADE
);