CREATE TABLE REGISTERED2 (
COURSENO VARCHAR (9),
IDNO CHAR(13),
GRADE VARCHAR(100),
CONSTRAINT PK_REGISTERED2 PRIMARY KEY (COURSENO, IDNO),
CONSTRAINT FK_CNO FOREIGN KEY (COURSENO) REFERENCES COURSE,
CONSTRAINT FK_IDNO FOREIGN KEY (IDNO) REFERENCES STUDENTS
);
