DROP TABLE COURSE; --TO DELETE THE TABLE

CREATE TABLE COURSE (
COMPCODE NUMERIC (4),
COURSENO VARCHAR (9) NOT NULL,
COURSE_NAME VARCHAR (20),
UNITS NUMERIC (2) NOT NULL,
UNIQUE (COMPCODE, COURSENO) --TABLE LEVEL CONSTRAINT
);