SELECT AVG(UNITPRICE) AS AVG_PRICE 
FROM INGREDIENTS
WHERE VENDORID IN (SELECT VENDORID FROM VENDORS WHERE
	COMPANYNAME = 'VEGGIES_R_US');

SELECT NAME
FROM INGREDIENTS 
WHERE INVENTORY BETWEEN
(SELECT AVG(INVENTORY) * 0.75 FROM INGREDIENTS)
AND
(SELECT AVG(INVENTORY) * 1.25 FROM INGREDIENTS);

SELECT * FROM INGREDIENTS

SELECT COMPANYNAME FROM VENDORS
WHERE REFERREDBY IN (SELECT VENDORID FROM VENDORS WHERE COMPANYNAME = 'VEGGIES_R_US')
AND
VENDORID IN (SELECT VENDORID FROM INGREDIENTS WHERE FOODGROUP = 'MILK'); 

SELECT NAME, UNITPRICE
FROM INGREDIENTS
WHERE VENDORID IN (SELECT VENDORID FROM VENDORS WHERE COMPANYNAME = 'VEGGIES_R_US');

SELECT NAME, PRICE
FROM ITEMS
WHERE ITEMID IN (SELECT ITEMID FROM MADEWITH WHERE INGREDIENTID IN
(SELECT INGREDIENTID FROM INGREDIENTS WHERE VENDORID IN
(SELECT VENDORID FROM VENDORS WHERE COMPANYNAME = 'VEGGIES_R_US')));

SELECT COMPANYNAME FROM VENDORS
WHERE VENDORID NOT IN
(SELECT VENDORID FROM INGREDIENTS
WHERE INVENTORY > 100 AND VENDORID IS NOT NULL)

SELECT * FROM INGREDIENTS
SELECT * FROM VENDORS

SELECT * FROM VENDORS

SELECT COMPANYNAME 
FROM VENDORS
WHERE REFERREDBY NOT IN
(SELECT VENDORID
FROM VENDORS
WHERE COMPANYNAME = 'NO SUCH COMPANY');

SELECT NAME
FROM ITEMS WHERE PRICE > ANY
(SELECT PRICE FROM ITEMS WHERE NAME LIKE '%SALAD');

SELECT * FROM ITEMS;

SELECT INGREDIENTID
FROM INGREDIENTS
WHERE VENDORID NOT IN
(SELECT VENDORID FROM VENDORS
WHERE COMPANYNAME = 'VEGGIES_R_US' OR COMPANYNAME = 'SPRING WATER SUPPLY'); 

SELECT name
FROM ingredients
WHERE ingredientid NOT IN
(SELECT ingredientid
FROM ingredients WHERE vendorid = ANY
(SELECT vendorid
FROM vendors
WHERE companyname = 'Veggies_R_Us' OR companyname
= 'Spring Water Supply'));

SELECT * FROM INGREDIENTS

SELECT NAME 
FROM INGREDIENTS
WHERE UNITPRICE >= ALL
(SELECT UNITPRICE 
FROM INGREDIENTS ING JOIN MADEWITH MW
ON MW.ingredientid = ING.INGREDIENTID JOIN ITEMS I ON
MW.ITEMID = I.ITEMID WHERE I.NAME LIKE '%SALAD');

SELECT ITEMID. NAME FROM ITEMS
WHERE (SELECT COUNT(*)
FROM MADEWITH
WHERE MADEWITH.ITEMID = ITEMS.ITEMID) >= 3;

SELECT VENDORID FROM VENDORS V1
WHERE (SELECT COUNT(*) FROM VENDORS V2 WHERE V1.VENDORID = V2.REFERREDBY) >= 2;

SELECT NAME, MEALID FROM MEALS
WHERE MEALID IN 
(SELECT MEALID FROM PARTOF WHERE ITEMID IN
(SELECT ITEMID FROM MADEWITH
WHERE INGREDIENTID IN
(SELECT ingredientid FROM INGREDIENTS
WHERE FOODGROUP = 'MILK')));

SELECT * FROM meals m
WHERE EXISTS
(SELECT *
FROM partof p JOIN items on p.itemid=items.itemid
JOIN madewith on items.itemid=madewith.itemid
JOIN ingredients on madewith.ingredientid=ingredients.ingredientid WHERE
foodgroup = 'Milk' AND m.mealid = p.mealid);

SELECT VENDORID FROM VENDORS
WHERE VENDORID NOT IN
(SELECT REFERREDBY FROM VENDORS WHERE REFERREDBY IS NOT NULL);

SELECT vendorid, companyname
FROM vendors v1
WHERE NOT EXISTS (SELECT *
FROM vendors v2
WHERE v2.referredby = v1.vendorid);

SELECT name, vendorid, unitprice * inventory as val FROM ingredients i
WHERE foodgroup IN ('Fruit', 'Vegetable')

SELECT name, companyname, val
FROM vendors v,
(SELECT name, vendorid, unitprice * inventory as val FROM ingredients i
WHERE foodgroup IN ('Fruit', 'Vegetable') ) d WHERE v.vendorid =
d.vendorid;

SELECT VENDORID
FROM INGREDIENTS,
(SELECT VENDORID, COUNT(*) AS 'TOT' FROM INGREDIENTS WHERE VENDORID IS NOT NULL GROUP BY VENDORID ) D1
WHERE D1.TOT > (SELECT TOT FROM D1 WHERE VENDORID IN 
(SELECT VENDORID FROM VENDORS WHERE COMPANYNAME = 'SPRING WATER SUPPLY'));

SELECT VENDORID, COUNT(*)
FROM INGREDIENTS
GROUP BY VENDORID
HAVING COUNT(*) > (SELECT COUNT(*) FROM INGREDIENTS ING
JOIN VENDORS V ON ING.VENDORID = V.VENDORID
WHERE V.COMPANYNAME = 'SPRING WATER SUPPLY');

SELECT VENDORID, AVG(INVENTORY * UNITPRICE)
FROM ingredients
GROUP BY VENDORID
HAVING VENDORID IN
(SELECT REFERREDBY FROM VENDORS WHERE REFERREDBY IS NOT NULL );

SELECT v1.vendorid, AVG(unitprice * inventory)
FROM ingredients JOIN vendors v1 ON (ingredients.vendorid=v1.vendorid)
GROUP BY v1.vendorid
HAVING EXISTS (SELECT *
FROM vendors v2
WHERE v1.vendorid = v2.referredby);

SELECT * FROM VENDORS;

SELECT I.ITEMID, V.VENDORID
FROM ITEMS I JOIN MADEWITH MW ON I.ITEMID = MW.ITEMID JOIN
INGREDIENTS ING ON ING.INGREDIENTID = MW.INGREDIENTID JOIN VENDORS V
ON V.VENDORID = ING.VENDORID
WHERE 
NOT EXISTS
((SELECT MW.ingredientid FROM MADEWITH WHERE MW.ITEMID = I.ITEMID)
EXCEPT
(SELECT ING.ingredientid FROM INGREDIENTS WHERE ING.VENDORID = V.VENDORID));

SELECT name, companyname
FROM items it, vendors v
WHERE NOT EXISTS (
SELECT ingredientid -- ingredients supplied by vendor
FROM ingredients i
WHERE i.vendorid = v.vendorid
EXCEPT
SELECT ingredientid -- ingredients used in item
FROM madewith m
WHERE it.itemid = m.itemid);

SELECT NAME, COMPANYNAME
FROM ITEMS I, VENDORS V
WHERE 
NOT EXISTS
((SELECT INGREDIENTID FROM MADEWITH MW WHERE MW.ITEMID = I.ITEMID)
EXCEPT
(SELECT INGREDIENTID FROM INGREDIENTS ING WHERE ING.VENDORID = V.VENDORID));

SELECT SUBSTRING(repfname, 1, 1) +'.' + replname AS name FROM vendors;

SELECT REPFNAME FROM VENDORS;

SELECT DISTINCT(itemid)
FROM madewith mw, ingredients ing
WHERE mw.ingredientid = ing.ingredientid AND ing.name != 'Cheese';

SELECT * FROM INGREDIENTS;

SELECT * FROM MADEWITH

SELECT * FROM ITEMS;

SELECT companyname
FROM vendors
WHERE companyname LIKE '%''%' ;

SELECT * FROM VENDORS