SELECT NAME 
FROM INGREDIENTS
WHERE VENDORID =
(SELECT VENDORID FROM 
VENDORS WHERE COMPANYNAME
= 'vEGGIES_R_US');


SELECT NAME
FROM INGREDIENTS
WHERE VENDORID IN
(SELECT VENDORID
FROM VENDORS 
WHERE COMPANYNAME = 'VEGGIES_R_US' OR COMPANYNAME
= 'SPRING WATER SUPPLY');

SELECT AVG(UNITPRICE) AS AVGPRICE
FROM INGREDIENTS
WHERE VENDORID IN
(SELECT VENDORID
FROM VENDORS
WHERE COMPANYNAME = 'VEGGIES_R_US');


SELECT NAME
FROM INGREDIENTS
WHERE INVENTORY BETWEEN
(SELECT AVG(INVENTORY) * 0.75
FROM INGREDIENTS)
AND
(SELECT AVG(INVENTORY) * 1.25 FROM
INGREDIENTS);

SELECT COMPANYNAME FROM
VENDORS WHERE 
(REFERREDBY IN
(SELECT VENDORID
FROM VENDORS
WHERE COMPANYNAME = 'VEGGIES_R_US')) AND
(VENDORID IN (SELECT
VENDORID
FROM INGREDIENTS
WHERE FOODGROUP = 'MILK'));

SELECT STOREID, SUM(PRICE) AS SALES
FROM ORDERS
WHERE MENUITEMID IN
	(SELECT ITEMID
	FROM MADEWITH
	WHERE INGREDIENTID IN
		(SELECT INGREDIENTID
		FROM INGREDIENTS
		WHERE VENDORID  =
			(SELECT VENDORID
			FROM VENDORS
			WHERE COMPANYNAME = 'VEGGIES_R_US')))
GROUP BY STOREID
HAVING COUNT(*) > 2
ORDER BY SALES DESC;			

SELECT NAME
FROM INGREDIENTS
WHERE VENDORID NOT IN(SELECT VENDORID 
FROM VENDORS WHERE COMPANYNAME = 'VEGGIES_R_US')

SELECT COMPANYNAME 
FROM VENDORS
WHERE VENDORID NOT IN(SELECT VENDORID 
FROM INGREDIENTS WHERE INVENTORY > 100 AND VENDORID IS NOT NULL);

SELECT COMPANYNAME 
FROM VENDORS
WHERE VENDORID NOT IN(SELECT VENDORID 
FROM INGREDIENTS WHERE INVENTORY > 100);

SELECT COMPANYNAME 
FROM VENDORS
where companyname = 'don''s dairy';

SELECT COMPANYNAME FROM VENDORS
WHERE REFERREDBY = 
(SELECT VENDORID
FROM VENDORS
WHERE COMPANYNAME = 'NO SUCH COMPANY');

SELECT companyname
FROM vendors
WHERE referredby NOT IN
(SELECT vendorid
FROM vendors
WHERE companyname = 'No Such Company');

SELECT DISTINCT ITEMS.ITEMID, PRICE
FROM ITEMS JOIN MADEWITH ON ITEMS.itemid= MADEWITH.iTEMID
WHERE INGREDIENTID IN
(SELECT INGREDIENTID
FROM INGREDIENTS JOIN VENDORS ON VENDORS.VENDORID = INGREDIENTS.VENDORID
WHERE COMPANYNAME = 'VEGGIES_R_US');

SELECT NAME
FROM ITEMS WHERE PRICE > ANY
(SELECT PRICE FROM ITEMS
WHERE NAME LIKE '%SALAD');

SELECT * FROM ITEMS;

SELECT PRICE FROM ITEMS
WHERE NAME LIKE '%SALAD';

--IMPORTANT TO CARE FOR THE NULL CASES
SELECT NAME
FROM INGREDIENTS
WHERE VENDORID NOT IN(
SELECT VENDORID 
FROM VENDORS 
WHERE COMPANYNAME  =  'VEGGIES_R_US' OR companyname = 'SPRING WATER SUPPLY')
OR VENDORID IS NULL;

SELECT name
FROM ingredients
WHERE ingredientid NOT IN
(SELECT ingredientid
FROM ingredients WHERE vendorid = ANY
(SELECT vendorid
FROM vendors
WHERE companyname = 'Veggies_R_Us' OR companyname
= 'Spring Water Supply')); 

SELECT NAME
FROM INGREDIENTS
WHERE UNITPRICE >= ALL
(SELECT UNITPRICE
FROM INGREDIENTS ING JOIN MADEWITH MW ON
MW.ingredientid = ING.ingredientid JOIN ITEMS I ON
MW.ITEMID = I.ITEMID WHERE I.NAME LIKE '%SALAD');
