SELECT * FROM INGREDIENTS;
BEGIN TRANSACTION T1;
	UPDATE ingredients SET INVENTORY = INVENTORY + 10;

SELECT * FROM ingredients;

COMMIT;

SELECT * FROM INGREDIENTS;

BEGIN TRANSACTION T2;
UPDATE INGREDIENTS SET INVENTORY = INVENTORY - 20;
SELECT * FROM INGREDIENTS;

ROLLBACK;

SELECT * FROM INGREDIENTS;

DELETE FROM DEPARTMENTS
WHERE CODE IN (SELECT CODE FROM DEPARTMENTS WHERE SUBDEPTOF = (SELECT CODE FROM DEPARTMENTS WHERE NAME = 'ADMINISTRATION'))
OR NAME = 'ADMINISTRATION';

DELETE FROM DEPARTMENTS
WHERE CODE IN (SELECT CODE FROM DEPARTMENTS WHERE SUBDEPTOF = (SELECT CODE FROM DEPARTMENTS WHERE NAME = 'ADMINISTRATION'));

DELETE FROM DEPARTMENTS
WHERE SUBDEPTOF = (SELECT CODE FROM DEPARTMENTS WHERE NAME = 'ADMINISTRATION');

SELECT * FROM DEPARTMENTS


--1

EXEC sp_MSforeachtable"ALTER TABLE ? NOCHECK CONSTRAINT ALL";

--2

BEGIN TRANSACTION T2;
SAVE TRANSACTION S1;
EXEC sp_MSforeachtable"ALTER TABLE ? NOCHECK CONSTRAINT ALL";

	DELETE FROM DEPARTMENTS
	WHERE CODE IN (SELECT CODE FROM DEPARTMENTS WHERE SUBDEPTOF = (SELECT CODE FROM DEPARTMENTS WHERE NAME = 'ADMINISTRATION'))
	OR NAME = 'ADMINISTRATION';

ROLLBACK TRANSACTION S1;
COMMIT;

SELECT * FROM DEPARTMENTS

--1

SELECT *
FROM SYS.OBJECTS
WHERE NAME = N'15'

CREATE TABLE TEMP1
(NUM_STORE NUMERIC(2), CHAR_STORE VARCHAR(15), DATE_STORE DATE);





BEGIN
	DECLARE @NUM INTEGER;
	SET @NUM = N'15'

	IF @NUM < 25
	BEGIN

		DECLARE @COUNTER INTEGER;
		SET @COUNTER = 1;

		WHILE @COUNTER < 25
		BEGIN
			IF(@COUNTER = 5)
				INSERT INTO TEMP1(NUM_STORE, CHAR_STORE) VALUES
				(5, 'FIVE');
			ELSE IF(@COUNTER = 10)
				INSERT INTO TEMP1(NUM_STORE, CHAR_STORE) VALUES
				(10, 'TEN');
			ELSE IF(@COUNTER = 15)
				INSERT INTO TEMP1 VALUES
				(15, 'FIFTEEN', SYSDATETIME())
			ELSE IF(@COUNTER = 20)
				INSERT INTO TEMP1(NUM_STORE, CHAR_STORE) VALUES
				(20, 'TWENTY');
			ELSE
				INSERT INTO TEMP1(NUM_STORE) VALUES
				(@COUNTER);

			SET @COUNTER = @COUNTER + 1;

			

		END
	END

END

DROP TABLE TEMP1;
SELECT * FROM TEMP1;

DELETE FROM TEMP1;

